export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';

export const GET_DASHBOARD = 'GET_DASHBOARD';
export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const LOADED_DASHBOARD = 'LOADED_DASHBOARD';
export const SELECT_DATE_DASHBOARD = 'SELECT_DATE_DASHBOARD';

export const TOGGLE_DATE_POPUP = 'TOGGLE_DATE_POPUP';
export const TOGGLE_NEW_POPUP = 'TOGGLE_NEW_POPUP';
export const TOGGLE_SEARCH_POPUP = 'TOGGLE_SEARCH_POPUP';
export const TOGGLE_STATUS_POPUP = 'TOGGLE_STATUS_POPUP';
export const TOGGLE_VIEW_PRODUCT = 'TOGGLE_VIEW_PRODUCT';
export const TOGGLE_VIEW_EXPENSE = 'TOGGLE_VIEW_EXPENSE';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOADED_PRODUCTS = 'LOADED_PRODUCTS';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SELECT_STATUS = 'SELECT_STATUS';
export const VIEW_PRODUCT = 'VIEW_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const BUY_PRODUCT = 'BUY_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const LOAD_INCOME = 'LOAD_INCOME';
export const LOADED_INCOME = 'LOADED_INCOME';
export const GET_ALL_INCOME = 'GET_ALL_INCOME';
export const SELECT_DATE_INCOME = 'SELECT_DATE_INCOME';
export const SEARCH_INCOME = 'SEARCH_INCOME';
export const CANCEL_PRODUCT = 'CANCEL_PRODUCT';

export const LOAD_EXPENSE = 'LOAD_EXPENSE';
export const LOADED_EXPENSE = 'LOADED_EXPENSE';
export const GET_ALL_EXPENSE = 'GET_ALL_EXPENSE';
export const NEW_EXPENSE = 'NEW_EXPENSE';
export const SELECT_DATE_EXPENSE = 'SELECT_DATE_EXPENSE';
export const SEARCH_EXPENSE = 'SEARCH_EXPENSE';
export const VIEW_EXPENSE = 'VIEW_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';